In [1]:
# 行业热点选择板块，板块里面筛选股票
import akshare as ak
import pandas as pd
# 关注排行榜
# stock_hot_follow_xq_df = ak.stock_hot_follow_xq(symbol="最热门")
# 讨论排行榜
# stock_hot_tweet_xq_df = ak.stock_hot_tweet_xq(symbol="最热门")
# 交易排行榜
stock_hot_deal_xq_df = ak.stock_hot_deal_xq(symbol="最热门")
# 人气榜-A股
stock_hot_rank_em_df = ak.stock_hot_rank_em()
# 飙升榜-A股
stock_hot_up_em_df = ak.stock_hot_up_em()

/home/liubei/miniconda3/envs/turtle/lib/python3.12/site-packages/py_mini_racer/py_mini_racer.py:15: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

  0%|          | 0/28 [00:00<?, ?it/s]

In [3]:
stock_hot_up_em_df.head(10)

   排名较昨日变动  当前排名        代码  股票名称    最新价       涨跌额    涨跌幅
0     4873   208  SZ301222  浙江恒威  35.01  5.149971  14.71
1     4773   514  SZ920748  路桥信息  47.27  5.941839  12.57
2     4602   515  SZ301581  黄山谷捷  51.74  3.797716   7.34
3     4478   691  SH688576  西山科技  86.00  8.806400  10.24
4     4291    87  SH603630  拉芳家化  21.33  2.135133  10.01
5     4179   705  SH605158  华达新材   8.81  0.385878   4.38
6     4139   516  SZ301210  金杨精密  38.79  2.199393   5.67
7     4112   651  SH603983  丸美生物  33.00  1.636800   4.96
8     4042   104  SH600156  华升股份   9.03  0.902097   9.99
9     3994  1456  SZ920123  芭薇股份  15.98  1.043494   6.53

In [7]:
stock_hot_deal_xq_df=stock_hot_deal_xq_df.rename(columns={"股票代码":"代码","股票简称":"股票名称"})

In [8]:
stock_hot_rank_em_df

    当前排名        代码  股票名称     最新价        涨跌额    涨跌幅
0      1  SZ002506  协鑫集成    4.16   0.418080  10.05
1      2  SZ002342  巨力索具   18.88   1.361248   7.21
2      3  SZ000592  平潭发展   11.83   1.188915  10.05
3      4  SH601212  白银有色   10.22  -1.026088 -10.04
4      5  SZ002131  利欧股份    8.82  -0.418950  -4.75
..   ...       ...   ...     ...        ...    ...
95    96  SZ002865  钧达股份  102.86 -10.286000 -10.00
96    97  SZ301636  泽润新能   92.60   3.241000   3.50
97    98  SZ300136  信维通信   77.82  -1.019442  -1.31
98    99  SZ001337  四川黄金   46.05  -4.508295  -9.79
99   100  SH600796  钱江生化    7.29   0.725355   9.95

[100 rows x 6 columns]

In [9]:
stock_hot_deal_xq_df

            代码  股票名称   关注      最新价
0     SH600519  贵州茅台  436  1555.00
1     SZ002594   比亚迪  249    90.11
2     SH600887  伊利股份  244    27.21
3     SH600036  招商银行  228    39.71
4     SH601919  中远海控  211    14.59
...        ...   ...  ...      ...
5554  SH603689  皖天然气    0     8.42
5555  SH603722   阿科力    0    38.31
5556  SZ300906   日月明    0    35.48
5557  SZ002259  升达林业    0     5.90
5558  SH688613  奥精医疗    0    22.19

[5559 rows x 4 columns]

In [10]:
import pandas as pd

df = pd.merge(stock_hot_deal_xq_df.head(200), stock_hot_rank_em_df.head(200), how='inner')
df

          代码  股票名称   关注      最新价  当前排名        涨跌额    涨跌幅
0   SH600519  贵州茅台  436  1555.00    10  30.633500   1.97
1   SZ300308  中际旭创  140   561.99    90   2.023164   0.36
2   SZ300059  东方财富  133    22.93    41   0.038981   0.17
3   SH601138  工业富联  129    53.88    71   0.474144   0.88
4   SH601899  紫金矿业  121    37.45    39  -1.636565  -4.37
5   SZ000547  航天发展   99    32.00     6  -0.492800  -1.54
6   SZ002050  三花智控   93    50.09    85  -1.522736  -3.04
7   SH603993  洛阳钼业   89    22.17    72  -1.405578  -6.34
8   SH600089  特变电工   80    27.63    45  -1.395315  -5.05
9   SZ300058  蓝色光标   75    19.13    16  -1.101888  -5.76
10  SH600410  华胜天成   73    21.89    68   0.019701   0.09
11  SZ002131  利欧股份   72     8.82     5  -0.418950  -4.75
12  SH601012  隆基绿能   69    18.23    63  -1.019057  -5.59
13  SZ300251  光线传媒   66    20.84    30   1.875600   9.00
14  SZ000592  平潭发展   63    11.83     3   1.188915  10.05
15  SZ300136  信维通信   62    77.82    98  -1.019442  -1.31
16  SZ002163  海南发展   59    17.89    51   0.805050   4.50
17  SH600118  中国卫星   51    92.23    83  -4.989643  -5.41
18  SH601933  永辉超市   50     4.75    54   0.219925   4.63
19  SZ002716  湖南白银   49    13.90    12  -1.385830  -9.97
20  SH600986  浙文互联   48    15.52     7   0.743408   4.79
21  SZ000981  山子高科   46     4.82    48  -0.300286  -6.23
22  SZ300300  海峡创新   45    14.52    15   2.904000  20.00
23  SZ002195  岩山科技   44     9.93    49  -0.157887  -1.59
24  SH600879  航天电子   44    26.09    64  -0.365260  -1.40
25  SZ002155  湖南黄金   44    32.71    23  -2.924274  -8.94
26  SZ300017  网宿科技   44    17.97    25   1.344156   7.48
27  SZ002413  雷科防务   42    14.65    35   0.454150   3.10
28  SZ002702  海欣食品   42     7.69    37   0.769769  10.01
29  SH603778  国晟科技   42    16.80    42   0.643440   3.83
30  SH601212  白银有色   41    10.22     4  -1.026088 -10.04
31  SZ002202  金风科技   39    24.82    14  -2.238764  -9.02
32  SZ300436   广生堂   38   131.02    92  16.953988  12.94
33  SZ000630  铜陵有色   38     7.19    38  -0.441466  -6.14

In [4]:
import akshare as ak

# stock_board_concept_name_em_df = ak.stock_board_concept_name_em()
# print(stock_board_concept_name_em_df)

stock_board_concept_cons_em_df = ak.stock_board_concept_cons_em(symbol="02GN2355")
print(stock_board_concept_cons_em_df)

ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

In [ ]:
stocke